[package]
name = "LNsimulator"
version = "0.1.0"
edition = "2021"


[dependencies]
petgraph = "0.6.4"
serde = "1.0.192"
serde_json = "1.0.108"
ordered-float = "4.1.1"
tokio = { version = "1.34.0", features = ["full"] }
rand = "0.8.5"
log = { version = "0.4", features = [] }
simplelog = "0.12.1"